name: Ahk2Exe

on: push

jobs:
  Example:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Scoop
        shell: powershell
        run: |
          pwd
          ls
          iwr -useb get.scoop.sh | iex
          scoop bucket add extras
          pwd
          ls
          
      - name: Add to environment variables
        shell: powershell
        run: Write-Output ('Path=' + $Env:SystemDrive + '\Windows\System32' + ';' + $Env:UserProfile + '\scoop\shims') >> $Env:GITHUB_ENV

      - name: Install AutoHotkey
        shell: powershell
        run: scoop install autohotkey

      - name: Ahk2Exe
        shell: powershell
        run: |
          where.exe "Ahk2Exe.exe"
          ls "C:\Users\runneradmin\scoop\apps\autohotkey\current\Compiler"
          type "C:\Users\runneradmin\scoop\apps\autohotkey\current\Compiler\readme.txt"
          ahk2exe /in "./MS Paint Hotkeys.ahk" /out "./msp hotkeys.exe" /icon ".github\readme-images\mspaint\icon\icon16.ico" /bin "C:\Users\runneradmin\scoop\shims\Unicode 64-bit.bin" /silent verbose
          ls
          ls C:\Users\runneradmin\scoop\shims
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build
          # A file, directory or wildcard pattern that describes what to upload
          path: "*.exe"
