name: Ahk2Exe

on: push

jobs:
  Example:
    name: Example
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: "MS Paint Hotkeys.ahk"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build
          path: ./*
