name: Ahk2Exe

on: push

jobs:
  Example:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Help me
        run: |
          pwd
          ls
      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: ".\\MS Paint Hotkeys.ahk"
          out: ".\\msp hotkeys.exe"
          icon: ".\\.github\readme-images\\mspaint\\icon\\icon16.ico"
      - name: Help me 2
        run: |
          pwd
          ls
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build
          path: ./*.exe
